user_with_phone_exists_error = "User with same phone number already exists"
